// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcessoSelecao.Infrastructure.Data;

#nullable disable

namespace ProcessoSelecao.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260903133136_AddBaremaTemplate")]
    partial class AddBaremaTemplate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProcessoSelecao.Domain.Entities.Avaliador", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AreaEspecializacao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Cargo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Instituicao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LinkLattes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NivelCnpq")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("ProcessoSelecaoId")
                        .HasColumnType("bigint");

                    b.Property<string>("SenhaHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("UltimaFormacao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ProcessoSelecaoId");

                    b.ToTable("Avaliadores");
                });

            modelBuilder.Entity("ProcessoSelecao.Domain.Entities.Barema", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AvaliadorId")
                        .HasColumnType("bigint");

                    b.Property<long>("CandidatoId")
                        .HasColumnType("bigint");

                    b.Property<string>("CriteriosJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataPreenchimento")
                        .HasColumnType("datetime2");

                    b.Property<float>("NotaFinal")
                        .HasColumnType("real");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long?>("TemplateId")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoBarema")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AvaliadorId");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("TemplateId");

                    b.ToTable("Baremas");
                });

            modelBuilder.Entity("ProcessoSelecao.Domain.Entities.BaremaItemAvaliacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BaremaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<float>("Nota")
                        .HasColumnType("real");

                    b.Property<long>("TemplateItemId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BaremaId");

                    b.HasIndex("TemplateItemId");

                    b.ToTable("BaremaItensAvaliacao");
                });

            modelBuilder.Entity("ProcessoSelecao.Domain.Entities.BaremaTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CriadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("PontoMaximo")
                        .HasColumnType("real");

                    b.Property<string>("TipoBarema")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("BaremaTemplates");
                });

            modelBuilder.Entity("ProcessoSelecao.Domain.Entities.BaremaTemplateItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("NotaMaxima")
                        .HasColumnType("real");

                    b.Property<float>("NotaMinima")
                        .HasColumnType("real");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("bit");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<float>("Passo")
                        .HasColumnType("real");

                    b.Property<string>("Secao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SecaoOrdem")
                        .HasColumnType("int");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("BaremaTemplateItems");
                });

            modelBuilder.Entity("ProcessoSelecao.Domain.Entities.Candidato", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AreaPesquisa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CampusProva")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CorRaca")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeficienciaAuditiva")
                        .HasColumnType("bit");

                    b.Property<bool>("DeficienciaFala")
                        .HasColumnType("bit");

                    b.Property<bool>("DeficienciaFisica")
                        .HasColumnType("bit");

                    b.Property<bool>("DeficienciaIntelectual")
                        .HasColumnType("bit");

                    b.Property<bool>("DeficienciaMental")
                        .HasColumnType("bit");

                    b.Property<bool>("DeficienciaMultipla")
                        .HasColumnType("bit");

                    b.Property<bool>("DeficienciaReabilitado")
                        .HasColumnType("bit");

                    b.Property<bool>("DeficienciaVisual")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EstadoNatal")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FormaInscricao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LocalProva")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MotivoOutrasNecessidades")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nacionalidade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Naturalidade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NomeSocial")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NumeroInscricao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Orientador")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PaisNatal")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("ProcessoSelecaoId")
                        .HasColumnType("bigint");

                    b.Property<string>("SenhaHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StatusValidacao")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Telefone2")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TipoVisto")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TituloProjeto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ValorInscricao")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ProcessoSelecaoId");

                    b.ToTable("Candidatos");
                });

            modelBuilder.Entity("ProcessoSelecao.Domain.Entities.Documento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CaminhoLocal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("CandidatoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashValidacao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MotivoRejeicao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<bool>("Validado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("ProcessoSelecao.Domain.Entities.ProcessoSelecao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AgenciaFomento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NivelBolsa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TipoProcesso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("VagasDisponiveis")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProcessosSelecao");
                });

            modelBuilder.Entity("ProcessoSelecao.Domain.Entities.Avaliador", b =>
                {
                    b.HasOne("ProcessoSelecao.Domain.Entities.ProcessoSelecao", "ProcessoSelecao")
                        .WithMany("Avaliadores")
                        .HasForeignKey("ProcessoSelecaoId");

                    b.Navigation("ProcessoSelecao");
                });

            modelBuilder.Entity("ProcessoSelecao.Domain.Entities.Barema", b =>
                {
                    b.HasOne("ProcessoSelecao.Domain.Entities.Avaliador", "Avaliador")
                        .WithMany("Baremas")
                        .HasForeignKey("AvaliadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcessoSelecao.Domain.Entities.Candidato", "Candidato")
                        .WithMany("Baremas")
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcessoSelecao.Domain.Entities.BaremaTemplate", "Template")
                        .WithMany("Baremas")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Avaliador");

                    b.Navigation("Candidato");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ProcessoSelecao.Domain.Entities.BaremaItemAvaliacao", b =>
                {
                    b.HasOne("ProcessoSelecao.Domain.Entities.Barema", "Barema")
                        .WithMany("ItensAvaliacao")
                        .HasForeignKey("BaremaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcessoSelecao.Domain.Entities.BaremaTemplateItem", "TemplateItem")
                        .WithMany()
                        .HasForeignKey("TemplateItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Barema");

                    b.Navigation("TemplateItem");
                });

            modelBuilder.Entity("ProcessoSelecao.Domain.Entities.BaremaTemplateItem", b =>
                {
                    b.HasOne("ProcessoSelecao.Domain.Entities.BaremaTemplate", "Template")
                        .WithMany("Itens")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ProcessoSelecao.Domain.Entities.Candidato", b =>
                {
                    b.HasOne("ProcessoSelecao.Domain.Entities.ProcessoSelecao", "ProcessoSelecao")
                        .WithMany("Candidatos")
                        .HasForeignKey("ProcessoSelecaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessoSelecao");
                });

            modelBuilder.Entity("ProcessoSelecao.Domain.Entities.Documento", b =>
                {
                    b.HasOne("ProcessoSelecao.Domain.Entities.Candidato", "Candidato")
                        .WithMany("Documentos")
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidato");
                });

            modelBuilder.Entity("ProcessoSelecao.Domain.Entities.Avaliador", b =>
                {
                    b.Navigation("Baremas");
                });

            modelBuilder.Entity("ProcessoSelecao.Domain.Entities.Barema", b =>
                {
                    b.Navigation("ItensAvaliacao");
                });

            modelBuilder.Entity("ProcessoSelecao.Domain.Entities.BaremaTemplate", b =>
                {
                    b.Navigation("Baremas");

                    b.Navigation("Itens");
                });

            modelBuilder.Entity("ProcessoSelecao.Domain.Entities.Candidato", b =>
                {
                    b.Navigation("Baremas");

                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("ProcessoSelecao.Domain.Entities.ProcessoSelecao", b =>
                {
                    b.Navigation("Avaliadores");

                    b.Navigation("Candidatos");
                });
#pragma warning restore 612, 618
        }
    }
}
