services:
  backend:
    build:
      context: ./src/backend
      dockerfile: ProcessoSelecao.Api/Dockerfile.dev
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ./src/backend:/src:Z
      - backend_cache:/src/.dotnet
      - ./documentos:/app/documentos:Z

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
      target: development
    environment:
      NG_HMR: 1
      NG_CLI_ANALYTICS: false
    volumes:
      - ./src/frontend:/app:Z
      - /app/node_modules
    command: ["sh", "-c", "if [ ! -d node_modules ] || [ -z \"$(ls -A node_modules 2>/dev/null)\" ]; then echo '>>> Instalando dependencias...' && npm install; fi && npm run start -- --port 80 --poll 2000"]
