# ==============================================
# Frontend - Blazor Server
# Dockerfile.dev — ambiente de desenvolvimento
# ==============================================

FROM mcr.microsoft.com/dotnet/sdk:10.0-alpine
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . .

EXPOSE 80

CMD ["dotnet", "watch", "--urls", "http://0.0.0.0:80"]
